service: default
runtime: python38

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 1
    memory_gb: 20
    disk_size_gb: 50

env_variables:
  MAPBOX_TOKEN: ${MAPBOX_TOKEN}

entrypoint: gunicorn -b 0.0.0.0:8080 app.app:server
